apiVersion: apps/v1
kind: Deployment
metadata:
    name : my-deploy1
    labels:
       app: my-app
spec:
  replicas: 2
  selector:
     matchLabels:
         app: my-app
  template:
    metadata:
       name: test-pod
       labels: 
          app: my-app
    spec:
       containers:
         - name: test-cont
           image: ajjurathod1998/test-image
           ports:
             - containerPort: 80  
